export let gameState = {
    mobs: [],
    flames: [],
    currentTarget: null,
    playerTyping: "",
    currentWave: 0,
    waveInProgress: false,
    nextWaveMessage: "",
    nextWaveMessageTimer: 0,
    damageFlash : 0,
    gameStarted: false,
    spawnDelay: 1000,
    mobsPerWave: 3,
    lives: 9,
};